services:
  - type: web
    name: messagewall
    env: node
    buildCommand: npm install && npm install --save-dev typescript @types/react @types/node @types/react-dom && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 18.19.1
    healthCheckPath: /
    autoDeploy: true
    numInstances: 1
    plan: starter 